name = "autobel-image-cache"
main = "image-cache-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "autobel-image-cache"
routes = [
  { pattern = "images.belautocenter.by/*", zone_name = "belautocenter.by" }
]

[env.development]
name = "autobel-image-cache-dev"
